spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

# Cloud SQL for MySQL
spring.datasource.url=jdbc:mysql://10.73.0.11:3306/javaapp

spring.datasource.username=root
spring.datasource.password=password

spring.datasource.hikari.initialization-fail-timeout=-1
